### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [Umbrus/Umbrus-archive#8]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_

Code included runs without any errors. It compiled with no problem -- great job!
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ **4 (Exceeds Expectations)**
* _Comment(s):_

Code produces the suite of functions and classes required of it and calls them in an appropriate order. All functions were there as according to the requirements, and most of them seemed to work as intended. There were a few functions that had bugs, and a couple of ways to refactor some of the code to be more efficient; but, in general, the code worked as intended. So really good job!
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_

Code is separated into distinct classes and functions each which are invoked for their own purposes. Honestly, the code did a wonderful job at separating out functionality into different functions. A notable case is the `__repr__` functions often side-loaded into a function that could be used later. Really great job!
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ **3 (Meets Expectations)**
* _Comment(s):_
 
Python language features are usually used, but there are 1-3 cases of a coded construction could have been accomplished by a Python builtin. The notable example is discussed in this [issue](https://github.com/Umbrus/Umbrus-archive/issues/5). However, in general, the code does a fine job at utilizing built-in Python functions to achieve an efficient solution. So, overall, good job!

### Overall Score: **15/16**

Overall, the project did a great job at implementing all the project requirements, separating them out into distinct functions and classes, and utilizing built-in Python functionality to accomplish these tasks. 

Moving forward, it will be very useful to take a deeper dive into how to best utilize dictionaries -- these data structures are incredibly useful and can be used super efficiently, especially with a deeper knowledge of them. So, I highly, highly suggest taking a deep dive into these structures and learning some best-practices with them (e.g. using `get()` function instead of the `in` operator where applicable). 

Other than that, some smaller things that might help would be: refactor the `try` and `except` clauses to only surround the line of code that might fail; researching [some ways](https://stackoverflow.com/questions/3090175/python-find-the-greatest-number-in-a-list-of-numbers) to grab the highest value from a list; and to be consistent with datatype usage across the entirety of a function or class.

That aside, the naming conventions, separation of functionality, and spacing were all highlights in this code base. Plus, the code actually achieved the functionality it intended. So, overall, nice job!

**Comment by Umbrus** [comment]
Thank you, Mr. McReynolds, for your review. I agree with all the comments. It's still a long way for me to learn how to write an elegant and clear code and I differently must learn how to use inbuilt functions more and how to pay attention to indents. I'm not that comfortable around dictionaries either, though I should.  I will continue to learn python, now in the introduction to data analysis.
I still have one little question about checking email.
I used the code like this:
############
 if "@" in email and ".com" in email: 
         return email 
  elif "@" in email and ".org" in email: 
         return email 
  else: 
         print("Something")
############
At the beginning I'd tried to write it shorter like this:
############
 if ("@" or ".com" or ".edu") in email: 
    return email 
############
but it hadn't worked out, it checked only for "@" and ".com". I've searched on the internet and couldn't get the answer.  Is there a way to write the character checking just in one line? Thank you.

**Comment by jmcrey** [comment]
@Umbrus 
Okay so great question. There _is_ actually a way to check the string all at once using a clever `for` loop and `if` statement. Here is an example:
```
email_patterns = ['@', '.com', '.edu', '.org']
if len([pattern for pattern in email_patterns if pattern in email]) == 2:
    print("I have an '@' symbol and a domain")
else:
    print("I am a malformed email address, or one that does not contain a supported domain")
```

Okay, now let's break this down a little bit. The variable `email_patterns` and the `print` statements are pretty self-explanatory, but let's focus on what's happening in that `if` statement. First, the `for` loop:

`[pattern for pattern in email_patterns if pattern in email]`

This code can be rewritten as follows:

```
found_symbols = list()
for pattern in email_patterns:
    if pattern in email:
        found_symbols.append(pattern)
```

The one-line for loop just combines all of this into one section. `for pattern in email_patterns` is the definition of the loop. `if pattern in email` is the condition we are testing, and `pattern` variable before the `for` key word correlates to the symbol we are looping on (e.g. '@', '.com', etc.). Finally, we wrap it all up in brackets (e.g. `[]`) to tell Python that we are making a list. Then, any `pattern` that satisfies the `if` condition is appended to this list. This is known as list comprehension, and you can read about another example [here](https://stackoverflow.com/questions/17321138/one-line-list-comprehension-if-else-variants).

Next, the reason why we are checking the length for 2 is that we know a valid email must contain the `@` symbol and a domain (e.g. '.com', '.edu', etc.). So, if the list returned is a length of 2, we can surmise that it contains an '@' and a domain. Obviously, there are some flaws with this assumption, such as this example would test true if an email contained a '.com' and '.edu', but no '@'. That being said, the best part about this example is that it is expandable. If we wanted to be more granular, we could do something like this:

```
email_patterns = ['@', '.com', '.edu', '.org']
found_symbols = [pattern for pattern in email_patterns if pattern in email]
if len(found_symbol) == 2 and found_symbol[0] == '@' and found_symbol[1].find('.') > -1:
     print("Valid email")
else:
    print("Malicious email")
```

Notice that this check actually same the same amount of time on average as the first check, but it is more comprehensive. But, I digress. In any case, the point is, yes -- through list comprehension, we can test all of these cases at once. If you have any more questions, please let me know!
